name: Tests

#on:
  #push:
    #branches:
    #- "dev"
    #- "main"
  #pull_request:
    #  branches:
    #- "dev"
    #- "main"

jobs:
  tests:
    name: Tests
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        #php: [8.2, 8.3]
        php: [8.2]
        database:
          #- mariadb:10.5
          #- mariadb:10.11
          - mariadb:11.5
          #- mysql:8
          #- mysql:9
    services:
      database:
        image: ${{ matrix.database }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: testing
        ports:
          - 3306
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Get cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php }}-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: bcmath, cli, curl, gd, mbstring, mysql, openssl, pdo, tokenizer, xml, zip
          tools: composer:v2
          coverage: none

      - name: Setup .env
        run: cp .env.ci .env

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist

      - name: Unit tests
        run: vendor/bin/phpunit --bootstrap vendor/autoload.php tests/Unit
        if: ${{ always() }}
        env:
          DB_HOST: UNIT_NO_DB

      - name: Integration tests
        run: vendor/bin/phpunit tests/Integration
        env:
          DB_PORT: ${{ job.services.database.ports[3306] }}
          DB_USERNAME: root
