name: Lint

on:
  push:
    branches:
      - 'develop'
      - '1.0-develop'
  pull_request:
    branches:
      - 'develop'
      - '1.0-develop'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: bcmath, curl, gd, mbstring, mysql, openssl, pdo, tokenizer, xml, zip
          tools: composer:v2
          coverage: none

      - name: Setup .env
        run: cp .env.ci .env

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist

      - name: PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff
