services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: panel
      MYSQL_USER: pyro
      MYSQL_PASSWORD: password
    volumes:
      - ./mariadb_data:/var/lib/mysql
    network_mode: host
    command: [
      '--default-authentication-plugin=mysql_native_password'
    ]

