version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: panel
      MYSQL_USER: pyro
      MYSQL_PASSWORD: password
    volumes:
      - ./mariadb_data:/var/lib/mysql
    network_mode: host
    command: [
      '--default-authentication-plugin=mysql_native_password'
    ]


# Add a custom initialization script

