version: "3.8"

services:
  pterodactyl-wings:
    image: ghcr.io/pterodactyl/wings:latest
    container_name: pterodactyl-wings
    restart: unless-stopped
    networks:
      - wings
    ports:
      - "8080:8080"
      - "2022:2022"
    environment:
      - TZ=America/Los_Angeles
      - WINGS_UID=1001
      - WINGS_GID=1001
      - WINGS_USERNAME=pyrodactyl
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers:/var/lib/docker/containers"
      - "./nix/pterodactyl/etc:/etc/pterodactyl"
      - "./nix/pterodactyl/lib:/var/lib/pterodactyl"
      - "./nix/pterodactyl/log:/var/log/pterodactyl"
      - "./nix/pterodactyl/tmp:/tmp/pterodactyl"

networks:
  wings:
    driver: bridge

