services:
  pterodactyl-wings:
    image: ghcr.io/pterodactyl/wings:latest
    container_name: pterodactyl-wings
    restart: unless-stopped
    network_mode: 'host'
    environment:
      - TZ=America/Los_Angeles
      - WINGS_UID=1001
      - WINGS_GID=1001
      - WINGS_USERNAME=pyrodactyl
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers:/var/lib/docker/containers"
      - "./etc:/etc/pterodactyl"
      - "./lib:/var/lib/pterodactyl"
      - "./log:/var/log/pterodactyl"
      - "./tmp:/tmp/pterodactyl"


